/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.SpinnerNumberModel;
import personas.Clientes;
import static procesos.ValidarRut.validarRut;

/**
 *
 * @author 19052403-5
 */
public class JfPrincipal extends javax.swing.JFrame {
    

    /**
     * Creates new form JfPrincipal
     */
    public JfPrincipal() {
        initComponents();
    }
    Clientes cli = new Clientes();
    
    public void llamarValidaRut(String rut){
        String rutAux=rut;
   
        if (validarRut(rutAux)){
            
        }else{
            this.formRegRut.setText("");
            this.jTextField1.setText("");
            this.formRegRut.requestFocus(true);
            lblRegErrorRut.setVisible(true);
                       
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fchImagen = new javax.swing.JFileChooser();
        jDialog1 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanRegistro = new javax.swing.JPanel();
        lblRegTitulo = new javax.swing.JLabel();
        sepTitulo = new javax.swing.JSeparator();
        lblRegRut = new javax.swing.JLabel();
        formRegRut = new javax.swing.JFormattedTextField();
        lblRegNombre = new javax.swing.JLabel();
        tfRegApepat = new javax.swing.JTextField();
        lblRegApePat = new javax.swing.JLabel();
        lblRegApeMat = new javax.swing.JLabel();
        lblRegTel = new javax.swing.JLabel();
        formRegFono = new javax.swing.JFormattedTextField();
        tfRegNombre = new javax.swing.JTextField();
        tfRegApeMat = new javax.swing.JTextField();
        lblRegEmail = new javax.swing.JLabel();
        tfRegEmail = new javax.swing.JTextField();
        lblRegPlan = new javax.swing.JLabel();
        cbPlanes = new javax.swing.JComboBox<>();
        LbDiaPago = new javax.swing.JLabel();
        spnFechaPagos = new javax.swing.JSpinner();
        SepRegDatos = new javax.swing.JSeparator();
        sepRegPlan = new javax.swing.JSeparator();
        btnRegRegistrar = new javax.swing.JButton();
        btnRegCancelar = new javax.swing.JButton();
        lblRegErrorRut = new javax.swing.JLabel();
        PanVerificacion = new javax.swing.JPanel();
        lblVerTitulo = new javax.swing.JLabel();
        sepVerTitulo = new javax.swing.JSeparator();
        lblVerRut = new javax.swing.JLabel();
        tfVerRut = new javax.swing.JFormattedTextField();
        btnVerConsultar = new javax.swing.JButton();
        sepRut = new javax.swing.JSeparator();
        lblVerNombre = new javax.swing.JLabel();
        tfVerNombre = new javax.swing.JTextField();
        lblVerApePat = new javax.swing.JLabel();
        tfVerApepat = new javax.swing.JTextField();
        lblVerApeMat = new javax.swing.JLabel();
        tfVerApeMat = new javax.swing.JTextField();
        lblVerFono = new javax.swing.JLabel();
        tfVerFono = new javax.swing.JFormattedTextField();
        lblVerEmail = new javax.swing.JLabel();
        tfVerEmail = new javax.swing.JTextField();
        lblVerRutBuscado = new javax.swing.JLabel();
        tfVerRutBuscado = new javax.swing.JFormattedTextField();
        sepVerDatos = new javax.swing.JSeparator();
        lblVerPlan = new javax.swing.JLabel();
        tfVerPlan = new javax.swing.JTextField();
        lblVerEstado = new javax.swing.JLabel();
        tfVerEstado = new javax.swing.JTextField();
        lblVerVencimiento = new javax.swing.JLabel();
        tfVerVencimiento = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel19 = new javax.swing.JLabel();
        btnVerLimpiar = new javax.swing.JButton();
        PanPagos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();

        fchImagen.setDialogType(javax.swing.JFileChooser.CUSTOM_DIALOG);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("El Rut ingresado no es valido");

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jButton1)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        PanRegistro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PanRegistroFocusGained(evt);
            }
        });

        lblRegTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRegTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegTitulo.setText("Registro de clientes");
        lblRegTitulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblRegTituloFocusGained(evt);
            }
        });

        lblRegRut.setText("RUT :");

        try {
            formRegRut.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formRegRut.setToolTipText("Ingrese el Rut del cliente");
        formRegRut.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        formRegRut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formRegRutFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formRegRutFocusLost(evt);
            }
        });

        lblRegNombre.setText("Nombre");

        lblRegApePat.setText("Apellido Paterno");

        lblRegApeMat.setText("Apellido Materno");

        lblRegTel.setText("Telefono ");

        try {
            formRegFono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("56#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblRegEmail.setText("E-Mail");

        lblRegPlan.setText("Plan a contratar");

        cbPlanes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plan Mensual", "Plan 6 Meses", "Plan Año" }));
        cbPlanes.setToolTipText("Seleccione el plan a contratar");
        cbPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPlanesActionPerformed(evt);
            }
        });

        LbDiaPago.setText("Dia de pago");
        LbDiaPago.setOpaque(true);
        LbDiaPago.setRequestFocusEnabled(false);
        LbDiaPago.setVerifyInputWhenFocusTarget(false);

        SpinnerNumberModel nm = new SpinnerNumberModel();
        nm.setMaximum(27);
        nm.setMinimum(1);
        spnFechaPagos.setModel(nm);
        spnFechaPagos.setEditor(new javax.swing.JSpinner.NumberEditor(spnFechaPagos, ""));
        spnFechaPagos.setValue(1);
        spnFechaPagos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                spnFechaPagosFocusLost(evt);
            }
        });

        btnRegRegistrar.setText("Registrar");
        btnRegRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegRegistrarActionPerformed(evt);
            }
        });

        btnRegCancelar.setText("Cancelar");
        btnRegCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegCancelarActionPerformed(evt);
            }
        });

        lblRegErrorRut.setVisible(false);
        lblRegErrorRut.setText("El rut ingresado no es valido, por favor, ingrese nuevamente");

        javax.swing.GroupLayout PanRegistroLayout = new javax.swing.GroupLayout(PanRegistro);
        PanRegistro.setLayout(PanRegistroLayout);
        PanRegistroLayout.setHorizontalGroup(
            PanRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sepTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(SepRegDatos, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(sepRegPlan, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(PanRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanRegistroLayout.createSequentialGroup()
                        .addComponent(lblRegPlan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbPlanes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LbDiaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnFechaPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanRegistroLayout.createSequentialGroup()
                        .addGroup(PanRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblRegTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRegRut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRegApePat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanRegistroLayout.createSequentialGroup()
                                .addGroup(PanRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(formRegFono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(tfRegApepat, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(PanRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblRegApeMat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblRegEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfRegNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(tfRegApeMat)
                                    .addComponent(tfRegEmail)))
                            .addGroup(PanRegistroLayout.createSequentialGroup()
                                .addComponent(formRegRut, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblRegNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                .addGap(138, 138, 138))))))
            .addGroup(PanRegistroLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnRegRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegCancelar)
                .addGap(130, 130, 130))
            .addGroup(PanRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegErrorRut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanRegistroLayout.setVerticalGroup(
            PanRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanRegistroLayout.createSequentialGroup()
                .addComponent(lblRegTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegErrorRut)
                .addGap(12, 12, 12)
                .addGroup(PanRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegRut)
                    .addComponent(lblRegNombre)
                    .addComponent(formRegRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRegNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegApePat, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfRegApepat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRegApeMat)
                        .addComponent(tfRegApeMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PanRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRegTel)
                    .addGroup(PanRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(formRegFono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRegEmail)
                        .addComponent(tfRegEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(SepRegDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(PanRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegPlan)
                    .addComponent(cbPlanes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbDiaPago)
                    .addComponent(spnFechaPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(sepRegPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(PanRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegRegistrar)
                    .addComponent(btnRegCancelar))
                .addGap(191, 191, 191))
        );

        jTabbedPane1.addTab("Registro de clientes", PanRegistro);

        lblVerTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblVerTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVerTitulo.setText("Verificacion de clientes");
        lblVerTitulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblVerTituloFocusGained(evt);
            }
        });

        lblVerRut.setText("RUT");

        try {
            tfVerRut.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnVerConsultar.setText("Consultar");
        btnVerConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerConsultarActionPerformed(evt);
            }
        });

        lblVerNombre.setText("Nombre");

        tfVerNombre.setEditable(false);

        lblVerApePat.setText("Apellido Paterno");

        tfVerApepat.setEditable(false);

        lblVerApeMat.setText("Apellido Materno");

        tfVerApeMat.setEditable(false);

        lblVerFono.setText("Telefono ");

        tfVerFono.setEditable(false);
        try {
            tfVerFono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("56#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblVerEmail.setText("E-Mail");

        tfVerEmail.setEditable(false);

        lblVerRutBuscado.setText("RUT");

        tfVerRutBuscado.setEditable(false);
        try {
            tfVerRutBuscado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfVerRutBuscado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVerRutBuscadoActionPerformed(evt);
            }
        });

        lblVerPlan.setText("Plan Contratado");

        tfVerPlan.setEditable(false);

        lblVerEstado.setText("Estado de plan");

        tfVerEstado.setEditable(false);
        tfVerEstado.setBackground(new java.awt.Color(255, 204, 51));
        tfVerEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfVerEstado.setForeground(new java.awt.Color(255, 255, 255));
        tfVerEstado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfVerEstado.setText("No hay datos");

        lblVerVencimiento.setText("Vencimiento");

        tfVerVencimiento.setEditable(false);

        jProgressBar1.setMaximum(30);
        jProgressBar1.setValue(15);
        jProgressBar1.setFocusable(false);
        jProgressBar1.setOpaque(true);
        jProgressBar1.setString("15 dias de 30");
        jProgressBar1.setStringPainted(true);

        jLabel19.setText("Algo que poner");

        btnVerLimpiar.setText("Limpiar Pantalla");

        javax.swing.GroupLayout PanVerificacionLayout = new javax.swing.GroupLayout(PanVerificacion);
        PanVerificacion.setLayout(PanVerificacionLayout);
        PanVerificacionLayout.setHorizontalGroup(
            PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVerTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
            .addComponent(sepVerTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(sepRut, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(sepVerDatos, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(PanVerificacionLayout.createSequentialGroup()
                .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanVerificacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanVerificacionLayout.createSequentialGroup()
                                .addComponent(lblVerRut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(tfVerRut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnVerConsultar))
                            .addGroup(PanVerificacionLayout.createSequentialGroup()
                                .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblVerFono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblVerApePat, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(lblVerRutBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfVerFono, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfVerApepat, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(tfVerRutBuscado))
                                .addGap(18, 18, 18)
                                .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblVerApeMat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblVerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblVerNombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfVerNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                    .addComponent(tfVerApeMat)
                                    .addComponent(tfVerEmail)))
                            .addGroup(PanVerificacionLayout.createSequentialGroup()
                                .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVerPlan)
                                    .addComponent(lblVerVencimiento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfVerPlan, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(tfVerVencimiento))
                                .addGap(18, 18, 18)
                                .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVerEstado)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(tfVerEstado)))))
                    .addGroup(PanVerificacionLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(btnVerLimpiar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanVerificacionLayout.setVerticalGroup(
            PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanVerificacionLayout.createSequentialGroup()
                .addComponent(lblVerTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepVerTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanVerificacionLayout.createSequentialGroup()
                        .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVerRut)
                            .addComponent(tfVerRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVerConsultar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sepRut, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanVerificacionLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfVerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblVerNombre)
                                        .addComponent(lblVerRutBuscado))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanVerificacionLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfVerRutBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVerApePat, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfVerApepat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblVerApeMat)
                                .addComponent(tfVerApeMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVerFono)
                            .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfVerFono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblVerEmail)
                                .addComponent(tfVerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(sepVerDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVerPlan)
                            .addComponent(tfVerPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVerEstado)
                            .addComponent(tfVerEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVerVencimiento)
                            .addComponent(tfVerVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(btnVerLimpiar)
                .addGap(79, 79, 79))
        );

        jTabbedPane1.addTab("Verificación de clientes", PanVerificacion);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pagos");

        jLabel3.setText("RUT");

        jButton3.setText("Buscar");

        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Tipo de plan", "Fecha pago", "Estado de Pago"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField1.setColumns(9);
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        javax.swing.GroupLayout PanPagosLayout = new javax.swing.GroupLayout(PanPagos);
        PanPagos.setLayout(PanPagosLayout);
        PanPagosLayout.setHorizontalGroup(
            PanPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(PanPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );
        PanPagosLayout.setVerticalGroup(
            PanPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanPagosLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pagos", PanPagos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained

    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void lblVerTituloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblVerTituloFocusGained
        this.setTitle("Verificacion de clientes");
    }//GEN-LAST:event_lblVerTituloFocusGained

    private void PanRegistroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PanRegistroFocusGained

    }//GEN-LAST:event_PanRegistroFocusGained

    private void cbPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlanesActionPerformed
        Cambio();
    }//GEN-LAST:event_cbPlanesActionPerformed

    private void lblRegTituloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblRegTituloFocusGained
        this.setTitle("Registro de clientes");
    }//GEN-LAST:event_lblRegTituloFocusGained

    private void btnVerConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerConsultarActionPerformed
        lblVerNombre.setVisible(true);
        tfVerNombre.setText("Camilo");
        tfVerNombre.setVisible(true);
    }//GEN-LAST:event_btnVerConsultarActionPerformed

    private void btnRegRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegRegistrarActionPerformed
        cli.setRut(this.formRegRut.getText());
        cli.setNombre(this.tfRegNombre.getText());
        cli.setApPat(this.tfRegApepat.getText());
        cli.setApMat(this.tfRegApeMat.getText());
        cli.setFono(Integer.parseInt(this.formRegFono.getText()));
        cli.setEmail(this.tfRegEmail.getText());
        cli.setIdSucursal(1);
        
    }//GEN-LAST:event_btnRegRegistrarActionPerformed

    private void formRegRutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formRegRutFocusLost
        lblRegErrorRut.setVisible(false);
        llamarValidaRut(this.formRegRut.getText());
    }//GEN-LAST:event_formRegRutFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        llamarValidaRut(this.jTextField1.getText());
    }//GEN-LAST:event_jTextField1FocusLost

    private void formRegRutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formRegRutFocusGained
        this.formRegRut.setText("");
    }//GEN-LAST:event_formRegRutFocusGained

    private void btnRegCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegCancelarActionPerformed
        this.formRegRut.setText("");
        this.lblRegErrorRut.setVisible(false);
    }//GEN-LAST:event_btnRegCancelarActionPerformed

    private void spnFechaPagosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spnFechaPagosFocusLost
        int ingreso= (int) this.spnFechaPagos.getValue();
        if (ingreso <= 1 && ingreso >= 27){
            
        }else{
            this.spnFechaPagos.setValue(1);
            System.err.println("Error");
        }
    }//GEN-LAST:event_spnFechaPagosFocusLost

    private void tfVerRutBuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVerRutBuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfVerRutBuscadoActionPerformed
    public void Cambio(){
        if (cbPlanes.getSelectedItem()== "Plan Mensual"){
            spnFechaPagos.setVisible(true);
            LbDiaPago.setVisible(true);
        }else{
            spnFechaPagos.setVisible(false);
            LbDiaPago.setVisible(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbDiaPago;
    private javax.swing.JPanel PanPagos;
    private javax.swing.JPanel PanRegistro;
    private javax.swing.JPanel PanVerificacion;
    private javax.swing.JSeparator SepRegDatos;
    private javax.swing.JButton btnRegCancelar;
    private javax.swing.JButton btnRegRegistrar;
    private javax.swing.JButton btnVerConsultar;
    private javax.swing.JButton btnVerLimpiar;
    private javax.swing.JComboBox<String> cbPlanes;
    private javax.swing.JFileChooser fchImagen;
    private javax.swing.JFormattedTextField formRegFono;
    private javax.swing.JFormattedTextField formRegRut;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblRegApeMat;
    private javax.swing.JLabel lblRegApePat;
    private javax.swing.JLabel lblRegEmail;
    private javax.swing.JLabel lblRegErrorRut;
    private javax.swing.JLabel lblRegNombre;
    private javax.swing.JLabel lblRegPlan;
    private javax.swing.JLabel lblRegRut;
    private javax.swing.JLabel lblRegTel;
    private javax.swing.JLabel lblRegTitulo;
    private javax.swing.JLabel lblVerApeMat;
    private javax.swing.JLabel lblVerApePat;
    private javax.swing.JLabel lblVerEmail;
    private javax.swing.JLabel lblVerEstado;
    private javax.swing.JLabel lblVerFono;
    private javax.swing.JLabel lblVerNombre;
    private javax.swing.JLabel lblVerPlan;
    private javax.swing.JLabel lblVerRut;
    private javax.swing.JLabel lblVerRutBuscado;
    private javax.swing.JLabel lblVerTitulo;
    private javax.swing.JLabel lblVerVencimiento;
    private javax.swing.JSeparator sepRegPlan;
    private javax.swing.JSeparator sepRut;
    private javax.swing.JSeparator sepTitulo;
    private javax.swing.JSeparator sepVerDatos;
    private javax.swing.JSeparator sepVerTitulo;
    private javax.swing.JSpinner spnFechaPagos;
    private javax.swing.JTextField tfRegApeMat;
    private javax.swing.JTextField tfRegApepat;
    private javax.swing.JTextField tfRegEmail;
    private javax.swing.JTextField tfRegNombre;
    private javax.swing.JTextField tfVerApeMat;
    private javax.swing.JTextField tfVerApepat;
    private javax.swing.JTextField tfVerEmail;
    private javax.swing.JTextField tfVerEstado;
    private javax.swing.JFormattedTextField tfVerFono;
    private javax.swing.JTextField tfVerNombre;
    private javax.swing.JTextField tfVerPlan;
    private javax.swing.JFormattedTextField tfVerRut;
    private javax.swing.JFormattedTextField tfVerRutBuscado;
    private javax.swing.JTextField tfVerVencimiento;
    // End of variables declaration//GEN-END:variables

}
